# Generated by Django 4.0.3 on 2022-04-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avgrain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avgrain',
            options={},
        ),
    ]
